[build]
  command = "npm run deploy"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[template.environment]
  GOOGLE_CLIENT_ID = "Your Google Client ID"
  GOOGLE_CLIENT_SECRET = "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"