[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "14" # or whichever version you're using

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"